/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.ControlAudiolibro;
import control.ControlCategoria;
import control.ControlNarrador;
import control.Control_Editorial;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.LinkedList;
import modelo.Audiolibro;
import modelo.Categoria;
import modelo.Editorial;
import modelo.Narrador;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class VistaAudiolibro extends javax.swing.JFrame {

    LinkedList<Audiolibro> listAuL;

    LinkedList<Narrador> listN;
    LinkedList<Editorial> listaE;
    LinkedList<Categoria> listaC;

    /**
     * Creates new form VistaAudiolibro
     */
    public VistaAudiolibro() {
        initComponents();

        setLocationRelativeTo(null);
        listAuL = new LinkedList<>();
        listN = new LinkedList<>();
        listaE = new LinkedList<>();
        listaC = new LinkedList<>();
        jDateChooser1.getDateEditor().setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldnumCap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxNarrador = new javax.swing.JComboBox<>();
        jComboBoxEditorial = new javax.swing.JComboBox<>();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        JSinopsis = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldNPaginas = new javax.swing.JTextField();
        jTextFieldDuracion = new javax.swing.JTextField();
        jTextFieldIDIOMA = new javax.swing.JTextField();
        btnAgregarAudiolibro = new javax.swing.JButton();
        btnEliminarAudiolibro = new javax.swing.JButton();
        btnModificarAudiolibro = new javax.swing.JButton();
        btnMostrarAudiolibro = new javax.swing.JButton();
        jTextFieldPortada = new javax.swing.JTextField();
        jTextFieldContrportada = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldReproducciones = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBoxClasificacion = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btSeleccionar = new javax.swing.JButton();
        btSeleccionar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Idioma:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Narrador:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Insertar audiolibro");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Editorial:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Número de páginas:");

        jTextFieldnumCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumCapActionPerformed(evt);
            }
        });
        jTextFieldnumCap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldnumCapKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Portada:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Contraportada:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Duración:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Sinopsis:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Número de capitulos:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Titulo:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Fecha creación:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Categoría:");

        jComboBoxEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEditorialActionPerformed(evt);
            }
        });

        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        JSinopsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSinopsisActionPerformed(evt);
            }
        });

        jTextFieldTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTituloKeyTyped(evt);
            }
        });

        jTextFieldNPaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNPaginasKeyTyped(evt);
            }
        });

        jTextFieldDuracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDuracionKeyTyped(evt);
            }
        });

        jTextFieldIDIOMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDIOMAActionPerformed(evt);
            }
        });
        jTextFieldIDIOMA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDIOMAKeyTyped(evt);
            }
        });

        btnAgregarAudiolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnInsertar.png"))); // NOI18N
        btnAgregarAudiolibro.setBorderPainted(false);
        btnAgregarAudiolibro.setContentAreaFilled(false);
        btnAgregarAudiolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAudiolibroActionPerformed(evt);
            }
        });

        btnEliminarAudiolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEliminar.png"))); // NOI18N
        btnEliminarAudiolibro.setBorderPainted(false);
        btnEliminarAudiolibro.setContentAreaFilled(false);
        btnEliminarAudiolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAudiolibroActionPerformed(evt);
            }
        });

        btnModificarAudiolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnModificar.png"))); // NOI18N
        btnModificarAudiolibro.setBorderPainted(false);
        btnModificarAudiolibro.setContentAreaFilled(false);
        btnModificarAudiolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAudiolibroActionPerformed(evt);
            }
        });

        btnMostrarAudiolibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMostrar.png"))); // NOI18N
        btnMostrarAudiolibro.setBorderPainted(false);
        btnMostrarAudiolibro.setContentAreaFilled(false);
        btnMostrarAudiolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAudiolibroActionPerformed(evt);
            }
        });

        jTextFieldPortada.setEditable(false);
        jTextFieldPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortadaActionPerformed(evt);
            }
        });

        jTextFieldContrportada.setEditable(false);
        jTextFieldContrportada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContrportadaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Id: ");

        jTextField1.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Reproducciones:");
        jLabel15.setToolTipText("");

        jTextFieldReproducciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldReproduccionesKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Calificación:");

        jComboBoxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buena", "Regular", "Mala" }));
        jComboBoxClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClasificacionActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy/MM/d");
        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });

        btSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSeleccionar.png"))); // NOI18N
        btSeleccionar.setBorderPainted(false);
        btSeleccionar.setContentAreaFilled(false);
        btSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionarActionPerformed(evt);
            }
        });

        btSeleccionar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSeleccionar.png"))); // NOI18N
        btSeleccionar2.setBorderPainted(false);
        btSeleccionar2.setContentAreaFilled(false);
        btSeleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionar2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(298, 298, 298)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEliminarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldContrportada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPortada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldnumCap, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btSeleccionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldIDIOMA, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxEditorial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxNarrador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxClasificacion, 0, 185, Short.MAX_VALUE)
                                        .addComponent(jTextFieldReproducciones)
                                        .addComponent(jComboBoxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(34, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(JSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldIDIOMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextFieldReproducciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBoxClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBoxNarrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBoxEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldPortada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextFieldContrportada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btSeleccionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldnumCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarAudiolibro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarAudiolibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarAudiolibro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //-------------------NARADORES-------------------
        ControlNarrador objpu = new ControlNarrador();
        listN = objpu.consultarNarrador();
        for (int i = 0; i < listN.size(); i++) {

            Narrador objetoPaisU = listN.get(i);
            jComboBoxNarrador.addItem(objetoPaisU.getNombre_narrador1());

        }

        //-------------------EDITORIALES-----------------
        Control_Editorial objpu2 = new Control_Editorial();
        listaE = objpu2.consultarEditoriales();
        for (int j = 0; j < listaE.size(); j++) {

            Editorial objetoPaisU2 = listaE.get(j);
            jComboBoxEditorial.addItem(objetoPaisU2.getNombre_editorial());

        }
        //------------------CATEGORIAS-------------------

        ControlCategoria objpu3 = new ControlCategoria();
        listaC = objpu3.consultarCategoria();
        for (int k = 0; k < listaC.size(); k++) {

            Categoria objetoPaisU3 = listaC.get(k);
            jComboBoxCategoria.addItem(objetoPaisU3.getCategoria());

        }


    }//GEN-LAST:event_formWindowOpened

    private void btnAgregarAudiolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAudiolibroActionPerformed
        String titulo = jTextFieldTitulo.getText();
        //String fecha_creacion = jDateChooser1.getText();
        jDateChooser1.setCalendar(Calendar.getInstance());

        Date fecha_creacion2 = jDateChooser1.getDate();

        long d = fecha_creacion2.getTime();

        java.sql.Date fecha_creacion = new java.sql.Date(d);//Se hace esto por que date entrega sabado domigo lunes etc, aqui se acomoda el formato con d al ponerle get time

        String num_paginas = jTextFieldNPaginas.getText();
        String duracion_total = jTextFieldDuracion.getText();
        String portada = jTextFieldPortada.getText();
        String contraportada = jTextFieldContrportada.getText();

        String calificacion = jComboBoxClasificacion.getSelectedItem().toString();
        String sipnosis = JSinopsis.getText();
        String numCapitulos = jTextFieldnumCap.getText();
        String idioma = jTextFieldIDIOMA.getText();
        String reproducciones = jTextFieldReproducciones.getText();
        String id_narradorAF = jComboBoxNarrador.getSelectedItem().toString();
        String id_editorialAF = jComboBoxEditorial.getSelectedItem().toString();
        String id_categoriaAF = jComboBoxCategoria.getSelectedItem().toString();

        int idN = 0;
        int idE = 0;
        int idC = 0;

        //----------NARRADOR-----------
        for (int x = 0; x < listN.size(); x++) {
            Narrador narradorsito = listN.get(x);
            if (id_narradorAF.equals(narradorsito.getNombre_narrador1())) {
                idN = narradorsito.getId_narrador();

            }
        }

        //----------Editorial----------
        for (int l = 0; l < listaE.size(); l++) {
            Editorial editoriales = listaE.get(l);
            if (id_editorialAF.equals(editoriales.getNombre_editorial())) {
                idE = editoriales.getId_editorial();

            }
        }

        //---------Categoria-----------
        for (int j = 0; j < listaC.size(); j++) {
            Categoria Categoria2 = listaC.get(j);
            if (id_categoriaAF.equals(Categoria2.getCategoria())) {
                idC = Categoria2.getId_categoria();

            }
        }

        //----VALIDAR (VACIO)---------
        //Se elimina cualquier espacio en blanco
        String TituloV = jTextFieldTitulo.getText().trim();
        String num_paginasV = jTextFieldNPaginas.getText().trim();
        String duracion_totalV = jTextFieldDuracion.getText().trim();
        String portadaV = jTextFieldPortada.getText().trim();
        String contraportadaV = jTextFieldContrportada.getText().trim();
        String sipnosisV = JSinopsis.getText().trim();
        String numCapitulosV = jTextFieldnumCap.getText().trim();
        String idiomaV = jTextFieldIDIOMA.getText().trim();
        String reproduccionesV = jTextFieldReproducciones.getText().trim();

        //Si no ha escrito nada
        if ((TituloV.isEmpty()) || (num_paginasV.isEmpty()) || (duracion_totalV.isEmpty()) || (portadaV.length() == 0) || (contraportadaV.length() == 0) || (sipnosisV.length() == 0) || (numCapitulosV.length() == 0) || (idiomaV.length() == 0) || (reproduccionesV.length() == 0)) {

            JOptionPane.showMessageDialog(this, "No puede haber campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(rootPane, "No se Inserto el AudioLibro");
        } else {
            Audiolibro objAL = new Audiolibro(titulo, fecha_creacion, Integer.parseInt(num_paginas), Double.parseDouble(duracion_total), portada, contraportada, calificacion, sipnosis, numCapitulos, idioma, Integer.parseInt(reproducciones), idN, idE, idC);
            ControlAudiolibro objcu = new ControlAudiolibro();
            boolean t = objcu.insertar_Audiolibro(objAL);
            if (t == true) {
                JOptionPane.showMessageDialog(rootPane, "Se inserto el AudioLibro con exito");
            } 
        }
    }//GEN-LAST:event_btnAgregarAudiolibroActionPerformed

    private void jComboBoxClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClasificacionActionPerformed

    private void btSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionarActionPerformed
        // TODO add your handling code here:

        //Creamos nuestra variable archivo en la cual podremos usar todos los metodos de la clase jFileChooser
        JFileChooser archivo = new JFileChooser();
        //Si deseamos crear filtros para la selecion de archivos
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG*.PNG)", "jpg", "jpeg","png");
        //Si deseas que se muestre primero los filtros usa la linea q esta abajo de esta.
        archivo.setFileFilter(filtro);
        // Agregamos el Filtro pero cuidado se mostrara despues de todos los archivos
        archivo.addChoosableFileFilter(filtro);

        archivo.setDialogTitle("Abrir Archivo");
        //Si deseamos que muestre una carpeta predetermina usa la siguiente linea
        //File ruta = new File("D:/productos");
        //Le implementamos a nuestro ventana de seleccion
        //archivo.setCurrentDirectory(ruta);

        int ventana = archivo.showOpenDialog(null);
        if (ventana == JFileChooser.APPROVE_OPTION) {

            File file = archivo.getSelectedFile();
            jTextFieldPortada.setText(String.valueOf(file));

        }


    }//GEN-LAST:event_btSeleccionarActionPerformed

    private void btSeleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionar2ActionPerformed
        // TODO add your handling code here:

        //Creamos nuestra variable archivo en la cual podremos usar todos los metodos de la clase jFileChooser
        JFileChooser archivo2 = new JFileChooser();
        //Si deseamos crear filtros para la selecion de archivos
        FileNameExtensionFilter filtro2 = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG,*.PNG)", "jpg", "jpeg","png");
        //Si deseas que se muestre primero los filtros usa la linea q esta abajo de esta.
        archivo2.setFileFilter(filtro2);
        // Agregamos el Filtro pero cuidado se mostrara despues de todos los archivos
        archivo2.addChoosableFileFilter(filtro2);

        archivo2.setDialogTitle("Abrir Archivo");

        int ventana2 = archivo2.showOpenDialog(null);
        if (ventana2 == JFileChooser.APPROVE_OPTION) {

            File file2 = archivo2.getSelectedFile();
            jTextFieldContrportada.setText(String.valueOf(file2));

        }


    }//GEN-LAST:event_btSeleccionar2ActionPerformed

    private void jComboBoxEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEditorialActionPerformed

    private void btnEliminarAudiolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAudiolibroActionPerformed
        // TODO add your handling code here:

        ControlAudiolibro objeu = new ControlAudiolibro();
        String selected = jTextField1.getText();
        boolean t1 = objeu.eliminarAudioLibro(selected);

        if (t1 == true) {
            JOptionPane.showMessageDialog(this, "Se elimino el Audiio Libro");
        } else {
            JOptionPane.showMessageDialog(this, "No se elimino el Audiio Libro");
        }


    }//GEN-LAST:event_btnEliminarAudiolibroActionPerformed

    private void btnMostrarAudiolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAudiolibroActionPerformed
        // TODO add your handling code here:

        ControlAudiolibro obju = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;

        listAuL = obju.consultarAudioLibro();
        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }


    }//GEN-LAST:event_btnMostrarAudiolibroActionPerformed

    private void JSinopsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSinopsisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JSinopsisActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        int selected = jTable2.rowAtPoint(evt.getPoint());

        jTextField1.setText(String.valueOf(jTable2.getValueAt(selected, 0)));
        jTextFieldTitulo.setText(String.valueOf(jTable2.getValueAt(selected, 1)));

        jTextFieldNPaginas.setText(String.valueOf(jTable2.getValueAt(selected, 3)));
        jTextFieldDuracion.setText(String.valueOf(jTable2.getValueAt(selected, 4)));
        jTextFieldPortada.setText(String.valueOf(jTable2.getValueAt(selected, 5)));
        jTextFieldContrportada.setText(String.valueOf(jTable2.getValueAt(selected, 6)));

        jComboBoxClasificacion.setSelectedItem(jTable2.getValueAt(selected, 7));
        JSinopsis.setText(String.valueOf(jTable2.getValueAt(selected, 8)));
        jTextFieldnumCap.setText(String.valueOf(jTable2.getValueAt(selected, 9)));
        jTextFieldIDIOMA.setText(String.valueOf(jTable2.getValueAt(selected, 10)));
        jTextFieldReproducciones.setText(String.valueOf(jTable2.getValueAt(selected, 11)));

        jComboBoxNarrador.setSelectedItem(jTable2.getValueAt(selected, 12));
        jComboBoxEditorial.setSelectedItem(jTable2.getValueAt(selected, 13));
        jComboBoxCategoria.setSelectedItem(jTable2.getValueAt(selected, 14));

        //obtenemos la fecha de dicha fila
        String fecha = jTable2.getValueAt(selected, 2).toString();
        //creamos el formato en el que deseamos mostrar la fecha
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-mm-dd");
        //creamos una variable tipo Date y la ponemos NULL
        Date fechaN = null;
        try {
            //parseamos de String a Date usando el formato
            fechaN = formatoDelTexto.parse(fecha);
            //seteamos o mostramos la fecha en el JDateChooser
            jDateChooser1.setDate(fechaN);

        } catch (ParseException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextFieldPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortadaActionPerformed

    private void btnModificarAudiolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAudiolibroActionPerformed
        // TODO add your handling code here:

        String select = jTextField1.getText();
        String titulo = jTextFieldTitulo.getText();
        // String fecha_creacion = jDateChooser1.getText();

        Date fecha_creacion2 = jDateChooser1.getDate();

        long f = fecha_creacion2.getTime();

        java.sql.Date fecha_creacion = new java.sql.Date(f);

        String num_paginas = jTextFieldNPaginas.getText();
        String duracion_total = jTextFieldDuracion.getText();
        String portada = jTextFieldPortada.getText();
        String contraportada = jTextFieldContrportada.getText();
        String calificacion = jComboBoxClasificacion.getSelectedItem().toString();
        String sipnosis = JSinopsis.getText();
        String numCapitulos = jTextFieldnumCap.getText();
        String idioma = jTextFieldIDIOMA.getText();
        String reproducciones = jTextFieldReproducciones.getText();
        String id_narradorAF = jComboBoxNarrador.getSelectedItem().toString();
        String id_editorialAF = jComboBoxEditorial.getSelectedItem().toString();
        String id_categoriaAF = jComboBoxCategoria.getSelectedItem().toString();

        int idN = 0;
        int idE = 0;
        int idC = 0;

        ControlAudiolibro objmu = new ControlAudiolibro();

        for (int x = 0; x < listN.size(); x++) {
            Narrador narradorsito = listN.get(x);
            if (id_narradorAF.equals(narradorsito.getNombre_narrador1())) {
                idN = narradorsito.getId_narrador();

            }
        }

        //----------Editorial----------
        for (int l = 0; l < listaE.size(); l++) {
            Editorial editoriales = listaE.get(l);
            if (id_editorialAF.equals(editoriales.getNombre_editorial())) {
                idE = editoriales.getId_editorial();

            }
        }

        //---------Categoria-----------
        for (int j = 0; j < listaC.size(); j++) {
            Categoria Categoria2 = listaC.get(j);
            if (id_categoriaAF.equals(Categoria2.getCategoria())) {
                idC = Categoria2.getId_categoria();

            }
        }

        if ((jTextFieldTitulo.getText().isEmpty()) || (jTextFieldNPaginas.getText().isEmpty()) || (jTextFieldDuracion.getText().isEmpty()) || (jTextFieldPortada.getText().isEmpty()) || (jTextFieldContrportada.getText().isEmpty()) || (JSinopsis.getText().isEmpty()) || (jTextFieldnumCap.getText().isEmpty()) || (jTextFieldIDIOMA.getText().isEmpty()) || (jTextFieldReproducciones.getText().isEmpty())) {
            JOptionPane.showMessageDialog(this, "No puede haber campos vacios", "Error", JOptionPane.ERROR_MESSAGE);
            JOptionPane.showMessageDialog(this, "No se modifico el Audiolibro");
        } else {
            boolean t1 = objmu.modificarAudioLibro(select, titulo, fecha_creacion, Integer.parseInt(num_paginas), Double.parseDouble(duracion_total), portada, contraportada, calificacion, sipnosis, numCapitulos, idioma, Integer.parseInt(reproducciones), idN, idE, idC);
            if (t1 == true) {
                JOptionPane.showMessageDialog(this, "Se modifico el Audiolibro con exito");
            } 
        }

    }//GEN-LAST:event_btnModificarAudiolibroActionPerformed

    private void jTextFieldContrportadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContrportadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContrportadaActionPerformed

    private void jTextFieldTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTituloKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldTituloKeyTyped

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void jTextFieldNPaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNPaginasKeyTyped
        // TODO add your handling code here:

        //VALIDAAAA QUE SOLO NUMEROS!!!!
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingrese un valor valido");
        }
    }//GEN-LAST:event_jTextFieldNPaginasKeyTyped

    private void jTextFieldIDIOMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDIOMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDIOMAActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jTextFieldDuracionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDuracionKeyTyped
        // TODO add your handling code here:

        //VALIDAAAA QUE SOLO NUMEROS!!!!
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingrese un valor valido");
        }

    }//GEN-LAST:event_jTextFieldDuracionKeyTyped

    private void jTextFieldnumCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumCapActionPerformed

    private void jTextFieldnumCapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldnumCapKeyTyped
        // TODO add your handling code here:

        //VALIDAAAA QUE SOLO NUMEROS!!!!
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingrese un valor valido");
        }


    }//GEN-LAST:event_jTextFieldnumCapKeyTyped

    private void jTextFieldReproduccionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldReproduccionesKeyTyped
        // TODO add your handling code here:

        //VALIDAAAA QUE SOLO NUMEROS!!!!
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(rootPane, "Ingrese un valor valido");
        }


    }//GEN-LAST:event_jTextFieldReproduccionesKeyTyped

    private void jTextFieldIDIOMAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDIOMAKeyTyped
        
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {

            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Por favor ingresa solo letras");
        }
        
    }//GEN-LAST:event_jTextFieldIDIOMAKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAudiolibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAudiolibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAudiolibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAudiolibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAudiolibro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JSinopsis;
    private javax.swing.JButton btSeleccionar;
    private javax.swing.JButton btSeleccionar2;
    private javax.swing.JButton btnAgregarAudiolibro;
    private javax.swing.JButton btnEliminarAudiolibro;
    private javax.swing.JButton btnModificarAudiolibro;
    private javax.swing.JButton btnMostrarAudiolibro;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxClasificacion;
    private javax.swing.JComboBox<String> jComboBoxEditorial;
    private javax.swing.JComboBox<String> jComboBoxNarrador;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldContrportada;
    private javax.swing.JTextField jTextFieldDuracion;
    private javax.swing.JTextField jTextFieldIDIOMA;
    private javax.swing.JTextField jTextFieldNPaginas;
    private javax.swing.JTextField jTextFieldPortada;
    private javax.swing.JTextField jTextFieldReproducciones;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JTextField jTextFieldnumCap;
    // End of variables declaration//GEN-END:variables
}
