/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.BaseDatos;
import control.ControlAudio;
import control.ControlAudiolibro;
import control.ControlAutor;
import control.ControlAutores_Libros;
import control.ControlCategoria;
import control.ControlNarrador;
import control.Control_Editorial;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Audio;
import modelo.Audiolibro;
import modelo.Autor;
import modelo.Autores_Libros;
import modelo.Categoria;
import modelo.Editorial;
import modelo.Narrador;

/**
 *
 * @author felipe
 */
public class VistaUmenu extends javax.swing.JFrame {

    LinkedList<Audiolibro> listAuL;
    LinkedList<Audio> listaAud;
    LinkedList<Categoria> listaC;
    LinkedList<Autor> listaA;
    LinkedList<Autores_Libros> listAuLibros;
    LinkedList<Editorial> listaE;
    LinkedList<Narrador> listaN;

    /**
     * Creates new form VistaUmenu
     */
    public VistaUmenu() {
        initComponents();
        listAuL = new LinkedList<>();
        listaAud = new LinkedList<>();
        listaC = new LinkedList<>();
        listaA = new LinkedList<>();
        listAuLibros = new LinkedList<>();
        listaE = new LinkedList<>();
        listaN = new LinkedList<>();
        
        txtsettitulo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtcorreo = new javax.swing.JTextField();
        txtcontraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnguardar = new javax.swing.JButton();
        txtsettitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnbuscart = new javax.swing.JButton();
        btnbuscarC = new javax.swing.JButton();
        btnbuscxAutor = new javax.swing.JButton();
        btnbuscarxE = new javax.swing.JButton();
        btnbuscarN = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btncs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(73, 181, 172));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Audiolibros:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Biblioteca", jPanel2);

        jPanel3.setBackground(new java.awt.Color(73, 181, 172));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Correo :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Contraseña :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel7.setText("Actualizar datos");

        jButton1.setText("ACTUALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtcontraseña))
                        .addGap(51, 51, 51)
                        .addComponent(jButton1)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1)))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuenta", jPanel3);

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));

        txtNombre.setBackground(new java.awt.Color(73, 181, 172));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnGuardar.png"))); // NOI18N
        btnguardar.setBorderPainted(false);
        btnguardar.setContentAreaFilled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtsettitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsettituloActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Escribe tu criterio de búsqueda:");

        jPanel4.setBackground(new java.awt.Color(73, 181, 172));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecciona tu opción de búsqueda:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        btnbuscart.setForeground(new java.awt.Color(0, 0, 255));
        btnbuscart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarportitulo.png"))); // NOI18N
        btnbuscart.setBorderPainted(false);
        btnbuscart.setContentAreaFilled(false);
        btnbuscart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscartActionPerformed(evt);
            }
        });

        btnbuscarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarporcategoria.png"))); // NOI18N
        btnbuscarC.setBorderPainted(false);
        btnbuscarC.setContentAreaFilled(false);
        btnbuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarCActionPerformed(evt);
            }
        });

        btnbuscxAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarporautor.png"))); // NOI18N
        btnbuscxAutor.setBorderPainted(false);
        btnbuscxAutor.setContentAreaFilled(false);
        btnbuscxAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscxAutorActionPerformed(evt);
            }
        });

        btnbuscarxE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarporeditorial.png"))); // NOI18N
        btnbuscarxE.setBorderPainted(false);
        btnbuscarxE.setContentAreaFilled(false);
        btnbuscarxE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarxEActionPerformed(evt);
            }
        });

        btnbuscarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarpornarrador.png"))); // NOI18N
        btnbuscarN.setBorderPainted(false);
        btnbuscarN.setContentAreaFilled(false);
        btnbuscarN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscart, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarxE, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscarN, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnbuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnbuscxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscxAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnbuscart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscarC, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnbuscarxE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addComponent(btnbuscarN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtsettitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsettitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar", jPanel1);

        jPanel5.setBackground(new java.awt.Color(73, 181, 172));

        btncs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCerrarSesion1.png"))); // NOI18N
        btncs.setBorderPainted(false);
        btncs.setContentAreaFilled(false);
        btncs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncsActionPerformed(evt);
            }
        });

        jLabel2.setText("Creado por: Felipe Giraldo, Cjay Zambrano");

        jLabel6.setText("Miguel Rojas y Frank Castillo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncs)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(btncs, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncsActionPerformed

        VistaLogin vcs = new VistaLogin();
        this.dispose();
        vcs.setVisible(true);

    }//GEN-LAST:event_btncsActionPerformed

    private void btnbuscarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarNActionPerformed

        ControlNarrador objce = new ControlNarrador();
        ControlAudiolibro objca = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;
        String narrador = txtNombre.getText();
        if (narrador.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor escribe algo para buscar");
        }

        listaN = objce.consultarAudioLibroPorNarrador(narrador);

        int idNarrador = 0;

        for (int i = 0; i < listaN.size(); i++) {
            Narrador narraty = listaN.get(i);

            if (narrador.equals(narraty.getNombre_narrador1())) {
                idNarrador = narraty.getId_narrador();
            }
        }
        listAuL = objca.consultarAudioLibroxNarrador(idNarrador);

        if (idNarrador == 0) {
            JOptionPane.showMessageDialog(this, "No hay audiolibros en esta categoria");
        }

        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }
    }//GEN-LAST:event_btnbuscarNActionPerformed

    private void btnbuscarxEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarxEActionPerformed

        Control_Editorial objce = new Control_Editorial();
        ControlAudiolibro objca = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;
        String editorial = txtNombre.getText();
        if (editorial.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor escribe algo para buscar");
        }

        listaE = objce.consultarAudioLibroPorEditorial(editorial);

        int idEditorial = 0;

        for (int i = 0; i < listaE.size(); i++) {
            Editorial editory = listaE.get(i);

            if (editorial.equals(editory.getNombre_editorial())) {
                idEditorial = editory.getId_editorial();
            }
        }
        listAuL = objca.consultarAudioLibroxEditorial(idEditorial);

        if (idEditorial == 0) {
            JOptionPane.showMessageDialog(this, "No hay audiolibros en esta categoria");
        }

        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }
    }//GEN-LAST:event_btnbuscarxEActionPerformed

    private void btnbuscxAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscxAutorActionPerformed

        ControlAutor objcA = new ControlAutor();
        ControlAutores_Libros objca = new ControlAutores_Libros();
        ControlAudiolibro objcAud = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;
        String autor = txtNombre.getText();
        if (autor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor escribe algo para buscar");
        }

        listaA = objcA.consultarAudioLibroPorAutor(autor);

        int idAutor = 0;

        for (int i = 0; i < listaA.size(); i++) {
            Autor author = listaA.get(i);

            if (autor.equals(author.getNombre_autor1())) {
                idAutor = author.getId_autor();
            }
        }
        listAuLibros = objca.consultarAudioLibroxAutor(idAutor);

        int idaudiolibro = 0;

        for (int i = 0; i < listAuLibros.size(); i++) {
            Autores_Libros authores = listAuLibros.get(i);

            if (idAutor == authores.getId_autorAF()) {
                idaudiolibro = authores.getId_audiolibroAF();
            }
        }

        listAuL = objcAud.consultarAudioLibroxAutor(idaudiolibro);

        if (idaudiolibro == 0) {
            JOptionPane.showMessageDialog(this, "No hay audiolibros en esta categoria");
        }

        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }
    }//GEN-LAST:event_btnbuscxAutorActionPerformed

    private void btnbuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarCActionPerformed

        ControlCategoria obju = new ControlCategoria();
        ControlAudiolibro objca = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;
        String categoria = txtNombre.getText();
        if (categoria.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor escribe algo para buscar");
        }

        listaC = obju.consultarAudioLibroPorcategoria(categoria);

        int idCategoria = 0;

        for (int i = 0; i < listaC.size(); i++) {
            Categoria category = listaC.get(i);

            if (categoria.equals(category.getCategoria())) {
                idCategoria = category.getId_categoria();
            }
        }
        listAuL = objca.consultarAudioLibroxCategoria(idCategoria);

        if (idCategoria == 0) {
            JOptionPane.showMessageDialog(this, "No hay audiolibros en esta categoria");
        }

        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }
    }//GEN-LAST:event_btnbuscarCActionPerformed

    private void btnbuscartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscartActionPerformed

        ControlAudiolibro obju = new ControlAudiolibro();
        int ncolu;
        Object[] fila2;
        String titulo = txtNombre.getText();
        if (titulo.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor escribe algo para buscar");
        }

        listAuL = obju.consultarAudioLibroBusqueda(titulo);

        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable2.setModel(modelo);
        modelo.addColumn("id_audiolibro");
        modelo.addColumn("titulo");
        modelo.addColumn("fecha_creacion");
        modelo.addColumn("num_paginas");
        modelo.addColumn("duracion_total");
        modelo.addColumn("portada");
        modelo.addColumn("contraportada");
        modelo.addColumn("calificacion");
        modelo.addColumn("sipnosis");
        modelo.addColumn("numCapitulos");
        modelo.addColumn("idioma");
        modelo.addColumn("reproducciones");
        modelo.addColumn("id_narradorAF");
        modelo.addColumn("id_editorialAF");
        modelo.addColumn("id_categoriaAF");
        ncolu = modelo.getColumnCount();

        for (int i = 0; i < listAuL.size(); i++) {

            fila2 = new Object[ncolu];
            fila2[0] = listAuL.get(i).getId_audiolibro();
            fila2[1] = listAuL.get(i).getTitulo();
            fila2[2] = listAuL.get(i).getFecha_creacion();
            fila2[3] = listAuL.get(i).getNum_paginas();
            fila2[4] = listAuL.get(i).getDuracion_total();
            fila2[5] = listAuL.get(i).getPortada();
            fila2[6] = listAuL.get(i).getContraportada();
            fila2[7] = listAuL.get(i).getCalificacion();
            fila2[8] = listAuL.get(i).getSipnosis();
            fila2[9] = listAuL.get(i).getNumCapitulos();
            fila2[10] = listAuL.get(i).getIdioma();
            fila2[11] = listAuL.get(i).getReproducciones();
            fila2[12] = listAuL.get(i).getId_narradorAF();
            fila2[13] = listAuL.get(i).getId_editorialAF();
            fila2[14] = listAuL.get(i).getId_categoriaAF();

            modelo.addRow(fila2);
        }
    }//GEN-LAST:event_btnbuscartActionPerformed

    private void txtsettituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsettituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsettituloActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed

        String select = txtsettitulo.getText();
        ControlAudio objcaud = new ControlAudio();
        int ncolu;
        Object[] fila2;

        listaAud = objcaud.consultarAudioBusqueda(select);
        DefaultTableModel modelo = new DefaultTableModel();
        this.jTable1.setModel(modelo);

        modelo.addColumn("archivo de audio");
        modelo.addColumn("id del audiolibro");
        ncolu = modelo.getColumnCount();

        for (int j = 0; j < listaAud.size(); j++) {
            fila2 = new Object[ncolu];
            fila2[0] = listaAud.get(j).getArchivo_Audio();
            fila2[1] = listaAud.get(j).getId_audiolibroF();
            modelo.addRow(fila2);

        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int selected = jTable2.rowAtPoint(evt.getPoint());
        txtsettitulo.setText(String.valueOf(jTable2.getValueAt(selected, 0)));
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarC;
    private javax.swing.JButton btnbuscarN;
    private javax.swing.JButton btnbuscart;
    private javax.swing.JButton btnbuscarxE;
    private javax.swing.JButton btnbuscxAutor;
    private javax.swing.JButton btncs;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcontraseña;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtsettitulo;
    // End of variables declaration//GEN-END:variables
}
