/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author felipe
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Btnusuario = new javax.swing.JButton();
        btnaudio = new javax.swing.JButton();
        btnAL = new javax.swing.JButton();
        btnAutor = new javax.swing.JButton();
        btncategoria = new javax.swing.JButton();
        btnNarrador = new javax.swing.JButton();
        btnpaisu = new javax.swing.JButton();
        btnpaisAutor = new javax.swing.JButton();
        btnPaisNa = new javax.swing.JButton();
        btnAutLi = new javax.swing.JButton();
        btnEditorial = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setText("Menú principal administrador");

        Btnusuario.setBackground(new java.awt.Color(33, 45, 62));
        Btnusuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Btnusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnUsuario.png"))); // NOI18N
        Btnusuario.setBorderPainted(false);
        Btnusuario.setContentAreaFilled(false);
        Btnusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnusuarioActionPerformed(evt);
            }
        });

        btnaudio.setBackground(new java.awt.Color(33, 45, 62));
        btnaudio.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnaudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnAudio.png"))); // NOI18N
        btnaudio.setBorderPainted(false);
        btnaudio.setContentAreaFilled(false);
        btnaudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaudioActionPerformed(evt);
            }
        });

        btnAL.setBackground(new java.awt.Color(33, 45, 62));
        btnAL.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnAudiolibro.png"))); // NOI18N
        btnAL.setBorderPainted(false);
        btnAL.setContentAreaFilled(false);
        btnAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALActionPerformed(evt);
            }
        });

        btnAutor.setBackground(new java.awt.Color(51, 0, 255));
        btnAutor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnAutor.png"))); // NOI18N
        btnAutor.setBorderPainted(false);
        btnAutor.setContentAreaFilled(false);
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });

        btncategoria.setBackground(new java.awt.Color(33, 45, 62));
        btncategoria.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btncategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCategoria1.png"))); // NOI18N
        btncategoria.setBorderPainted(false);
        btncategoria.setContentAreaFilled(false);
        btncategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriaActionPerformed(evt);
            }
        });

        btnNarrador.setBackground(new java.awt.Color(33, 45, 62));
        btnNarrador.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnNarrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnNarrador.png"))); // NOI18N
        btnNarrador.setBorderPainted(false);
        btnNarrador.setContentAreaFilled(false);
        btnNarrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNarradorActionPerformed(evt);
            }
        });

        btnpaisu.setBackground(new java.awt.Color(33, 45, 62));
        btnpaisu.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnpaisu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPaisusuario1.png"))); // NOI18N
        btnpaisu.setBorderPainted(false);
        btnpaisu.setContentAreaFilled(false);
        btnpaisu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaisuActionPerformed(evt);
            }
        });

        btnpaisAutor.setBackground(new java.awt.Color(33, 45, 62));
        btnpaisAutor.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnpaisAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPaisautor1.png"))); // NOI18N
        btnpaisAutor.setBorderPainted(false);
        btnpaisAutor.setContentAreaFilled(false);
        btnpaisAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpaisAutorActionPerformed(evt);
            }
        });

        btnPaisNa.setBackground(new java.awt.Color(33, 45, 62));
        btnPaisNa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnPaisNa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnPaisnarrador1.png"))); // NOI18N
        btnPaisNa.setBorderPainted(false);
        btnPaisNa.setContentAreaFilled(false);
        btnPaisNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaisNaActionPerformed(evt);
            }
        });

        btnAutLi.setBackground(new java.awt.Color(33, 45, 62));
        btnAutLi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAutLi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnAutoresDeLibros.png"))); // NOI18N
        btnAutLi.setBorderPainted(false);
        btnAutLi.setContentAreaFilled(false);
        btnAutLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutLiActionPerformed(evt);
            }
        });

        btnEditorial.setBackground(new java.awt.Color(33, 45, 62));
        btnEditorial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEditorial.png"))); // NOI18N
        btnEditorial.setBorderPainted(false);
        btnEditorial.setContentAreaFilled(false);
        btnEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorialActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoReaderPro.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Selecciona la entidad a la cual deseas ingresar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnaudio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAutor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(btnAutLi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnpaisAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btncategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(btnEditorial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNarrador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPaisNa, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(btnpaisu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btnusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPaisNa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpaisu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNarrador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnaudio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpaisAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutLi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnusuarioActionPerformed
        
        VistaUsuario vu = new VistaUsuario();
        this.dispose();
        vu.setVisible(true);
        vu.btnregist.setVisible(false);
        vu.btnregresar.setVisible(false);
        
    }//GEN-LAST:event_BtnusuarioActionPerformed

    private void btnpaisuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaisuActionPerformed
        
        VistaPais_Usuario vpu = new VistaPais_Usuario();
        this.dispose();
        vpu.setVisible(true);
        
    }//GEN-LAST:event_btnpaisuActionPerformed

    private void btnALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALActionPerformed

        VistaAudiolibro vaL = new VistaAudiolibro();
        this.dispose();
        vaL.setVisible(true);
        
    }//GEN-LAST:event_btnALActionPerformed

    private void btnaudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaudioActionPerformed
        
        VistaAudio vau = new VistaAudio();
        this.dispose();
        vau.setVisible(true);
        
    }//GEN-LAST:event_btnaudioActionPerformed

    private void btncategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriaActionPerformed
        
        VistaCategoria vc = new VistaCategoria();
        this.dispose();
        vc.setVisible(true);
        
    }//GEN-LAST:event_btncategoriaActionPerformed

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        
        VistaAutor va = new VistaAutor();
        this.dispose();
        va.setVisible(true);
        
    }//GEN-LAST:event_btnAutorActionPerformed

    private void btnpaisAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpaisAutorActionPerformed
        
        VistaPais_autorI vpa = new VistaPais_autorI();
        this.dispose();
        vpa.setVisible(true);
        
    }//GEN-LAST:event_btnpaisAutorActionPerformed

    private void btnAutLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutLiActionPerformed
        
        Vista_Autores_Libros vaL = new Vista_Autores_Libros();
        this.dispose();
        vaL.setVisible(true);
        
    }//GEN-LAST:event_btnAutLiActionPerformed

    private void btnNarradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNarradorActionPerformed
        
        VistaNarrador vn = new VistaNarrador();
        this.dispose();
        vn.setVisible(true);
        
    }//GEN-LAST:event_btnNarradorActionPerformed

    private void btnPaisNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaisNaActionPerformed
        
        VistaPais_narrador vpn = new VistaPais_narrador();
        this.dispose();
        vpn.setVisible(true);
        
    }//GEN-LAST:event_btnPaisNaActionPerformed

    private void btnEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorialActionPerformed
        
        Vista_Crear_Editorial ve = new Vista_Crear_Editorial();
        this.dispose();
        ve.setVisible(true);
        
    }//GEN-LAST:event_btnEditorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnusuario;
    private javax.swing.JButton btnAL;
    private javax.swing.JButton btnAutLi;
    private javax.swing.JButton btnAutor;
    private javax.swing.JButton btnEditorial;
    private javax.swing.JButton btnNarrador;
    private javax.swing.JButton btnPaisNa;
    private javax.swing.JButton btnaudio;
    private javax.swing.JButton btncategoria;
    private javax.swing.JButton btnpaisAutor;
    private javax.swing.JButton btnpaisu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
